### ISSUE TITLE
Should test for #define CM0PLUS not be CORE_CM0PLUS?

### ISSUE THREAD

**Issue by pieterconradie** [STMicroelectronics/stm32wlxx_hal_driver#3]
Hi there!

See here:
https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/main/Src/stm32wlxx_hal_subghz.c#L269
https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/main/Src/stm32wlxx_hal_subghz.c#L303
https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/main/Src/stm32wlxx_hal_subghz.c#L369

These line test if "CM0PLUS" is defined but the STM32CubeIDE generated dual core project defines "CORE_CM0PLUS". Is this a mistake?

thanks in advance,
Pieter

**Comment by ALABSTM** [comment]
Hi @pieterconradie,

Thank you for this question. This looks like a bug needing to be fixed. Another look to other drivers clearly shows the macro to check is `CORE_CM0PLUS`, not `CM0PLUS`.

https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/42e788df1344d9db4fcc99a81c6d2c3a5c4ba9bf/Inc/stm32wlxx_hal_comp.h#L384

https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/42e788df1344d9db4fcc99a81c6d2c3a5c4ba9bf/Inc/stm32wlxx_hal_rcc.h#L780

https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/42e788df1344d9db4fcc99a81c6d2c3a5c4ba9bf/Src/stm32wlxx_ll_exti.c#L107

This has been reported to our development teams. I'll get back to you as soon as I have their feedback.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 173061

**Comment by KRASTM** [comment]
Fixed in c3f558c56e6a34881cad7a735fd5347d451fcd94
