### ISSUE TITLE
Why is LL_GPIO_SetPinMode called twice in LL_GPIO_Init?

### ISSUE THREAD

**Issue by AJ528** [STMicroelectronics/stm32wlxx_hal_driver#6]
I was looking at the `LL_GPIO_Init` function and I noticed the function `LL_GPIO_SetPinMode` is called twice in this function. The first time is near the beginning of the function on line 178:
https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/d25d454a7b7120d99d4736066b3d0cbe5f1734a7/Src/stm32wlxx_ll_gpio.c#L178
The second time is at the end of the function on line 215:
https://github.com/STMicroelectronics/stm32wlxx_hal_driver/blob/d25d454a7b7120d99d4736066b3d0cbe5f1734a7/Src/stm32wlxx_ll_gpio.c#L215

By calling `LL_GPIO_SetPinMode` before the various GPIO parameters are configured, it can cause unexpected behavior on the pins. I was configuring port PA2 as LPUART1_TX, and it was unexpectedly outputting a byte over UART when being configured. Removing the `LL_GPIO_SetPinMode` on line 178 and only calling it on line 215 fixed this bug.

Unless there is some reason to call this function twice, I believe this is a bug.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 182334

**Comment by RJMSTM** [comment]
Fixed in : 5eda2310f3bad3778ca5424b9f15b3693219eed1
